### DISCUSSION TITLE
Avoid black frame around background image

### DISCUSSION THREAD

**Discussion by rngcntr** [MatthiasValvekens/pyHanko#224] [Q&A] [answered]
Hi there!

I've been trying to sign documents using a digital image of my actual signature for aesthetic reasons. However, I have not yet found a way to disable the black box that is drawn around the signature by pyHanko. Here is my `pyhanko.yaml`:

```yaml
stamp-styles:
  default:
    type: text
    background: signature.png
    stamp-text: ""
```

After reading the docs, my first thought was that I might not have configured `text-box-style` correctly. But much to my confusion, configuring `border_width` there adds a second box around the (in my case empty) text instead of altering the box around the image.

**signature.png**
![signature2](https://user-images.githubusercontent.com/7890887/220431638-ebe40425-c45b-4ed7-a2b9-faa7bd07bf09.png)

**Signed PDF File**
![image](https://user-images.githubusercontent.com/7890887/220431556-30b9e185-e08c-4c23-a791-1dc7c263e939.png)

Has anybody managed to find a solution for this problem? Thanks!

**Comment by MatthiasValvekens** [comment, marked as answer]
Hi @rngcntr,


Yeah, this isn't as obvious as it perhaps should be. The `border_width` param in `TextBoxStyle` is for the internal text box. You'll want to set it directly on the stamp style instead. In other words:

```yaml
stamp-styles:
  default:
    type: text
    background: signature.png
    stamp-text: ""
    border-width: 0
```

That should work.
