### DISCUSSION TITLE
How to completely disable margins/padding?

### DISCUSSION THREAD

**Discussion by seakrebel** [MatthiasValvekens/pyHanko#369] [Q&A]
I tried everything, but just can't remove margins completely. Does anyone know the trick?

I think it is around 10pt

```yaml
stamp-styles:
  default:
    type: text
    background:
    border_width: 0
    stamp-text: "Signed by: %(signer)s\nDate: %(ts)s"
    timestamp_format: "%Y-%m-%d"
    text-box-style:
      font_size: 10
    inner-content-layout:
      x-align: left
      y-align: bottom
      margins:
        left: 0
        right: 0
        top: 0
        bottom: 0
      inner-content-scaling: none
```

![Screenshot 2024-01-25 at 07 13 46@2x](https://github.com/MatthiasValvekens/pyHanko/assets/16282150/edc939a6-7216-4e58-a3fb-c41f03b9040e)
