### DISCUSSION TITLE
Where we find the PKCS#11 config file?

### DISCUSSION THREAD

**Discussion by satanu01** [MatthiasValvekens/pyHanko#43] [Q&A] [answered]
Where we find the config file for configuring the cert label changes/assignment purpose...

Like:
```
pkcs11-setups:
  test-setup:
    module-path: /usr/lib/libsofthsm2.so
    token-label: testrsa
    cert-label: signer
    user-pin: 1234
```
