### DISCUSSION TITLE
How to embed chain of trust in PDF

### DISCUSSION THREAD

**Discussion by Trefex** [MatthiasValvekens/pyHanko#444] [Q&A]
Hi,

I am able to sign PDFs using a PKCS#11 YubiKey device. So far so good.

However, when I open the PDF in Acrobat, I get a warning, because the certificate is not trusted, and upon inspection, it seems the issuance chain is not embedded into the PDF.

This is the command I used:

```
pyhanko --verbose sign addsig --field  1/100,100,400,200/Sig1 --with-validation-info --validation-context setup-a --timestamp-url https://freetsa.org/tsr pkcs11 --p11-setup test-setup input.pdf signed.pdf
```

```
cat pyhanko.yml
pkcs11-setups:
   test-setup:
       module-path: /usr/local/lib/libykcs11.dylib
       token-criteria:
           label: 'YubiKey PIV #xxxxxx'
       cert-id: 02
       key-id: 02
       user-pin: xxxxx
validation-contexts:
    setup-a:
        trust: 'CA.pem'
        trust-replace: true
        other-certs: 'interim.pem'
        signer-key-usage: ["digital_signature"]
```

Running validation with pyhanko however works

```
Bottom line
-----------
The signature is judged VALID
```

Would I have missed something?

Many thanks for any pointers.
T
