### DISCUSSION TITLE
Please provide option to add PNG image as signature in the signature widget

### DISCUSSION THREAD

**Discussion by ghoshpushpendu** [MatthiasValvekens/pyHanko#65] [Q&A] [answered]
Steps I Followed - 

add Signature Placeholder 
`pyhanko sign addfields --field  PAGE/X1,Y1,X2,Y2/NAME input.pdf output.pdf`

Sign PDF
`pyhanko sign addsig --field Sig1 pemder \
    --key key.pem --cert cert.pem input.pdf output.pdf`

This signs the PDF and create a rectangle with the signature.

But is there a way to add signature image like png there ?

**Comment by ghoshpushpendu** [comment]
I am new to python and a node js developer - so I think it ll take time for me to understand your code. @MatthiasValvekens

**Comment by MatthiasValvekens** [comment, marked as answer]
Yes, that's possible; see here: https://pyhanko.readthedocs.io/en/latest/cli-guide/config.html#styles-for-stamping-and-signature-appearances and https://pyhanko.readthedocs.io/en/latest/api-docs/pyhanko.stamp.html#pyhanko.stamp.BaseStampStyle.

In particular, note the following:

 - The `background` entry in a style definition can take a PNG image as its argument (or even another PDF).
 - You can leave the `stamp-text` empty.
 - There's a `background-opacity` option (which is only documented in the [API reference](https://pyhanko.readthedocs.io/en/latest/api-docs/pyhanko.stamp.html#pyhanko.stamp.BaseStampStyle) at this point, but it works in config as well) that allows you to have the background displayed with full opacity.

Combining these, it's possible to set up a signature appearance with only an image and no text:

```yaml
stamp-styles:
    bitmap-notext:
        type: text
        stamp-text: ""
        background: image.png
        background-opacity: 1
```

Would that work for you?

**Reply by MatthiasValvekens** [reply]
@ghoshpushpendu Note: I've migrated this question to a discussion, since I try to keep the issue tracker reserved for development work (bugs and feature requests). I prefer to handle questions here in the discussion space :)

**Reply by ghoshpushpendu** [reply]
Pretty straight forward ... I missed .. sorry .. my bad.

**Comment by ghoshpushpendu** [comment]
But still seems like we have less control on the signing text and image position.

**Reply by MatthiasValvekens** [reply]
Actually, those can be controlled as well, but it's again not documented outside of the API reference (clearly I should do something about that 😅).

Here's an example showing how you can (to a degree) control the position of the background image and the text box. Note that text alignment _within_ the text's bounding box is not something you can easily control right now, though.

```yaml
bitmap-demo:
        type: text
        stamp-text: "Test Test Test\n%(ts)s"
        background: image.png
        background-opacity: 1
        background-layout:
          x-align: left
          margins:
            left: 10
            top: 10
            bottom: 10
        inner-content-layout:
          x-align: right
          margins:
            right: 10
```

The layout code is pretty primitive though, since fancy graphics isn't what pyHanko is about. If you want something really fancy, you might be better off generating the appearance using (for example) an SVG to PDF converter, and use `background: svg-to-pdf-output.pdf` to use the generated PDF as a background.
