### ISSUE TITLE
Where we find the PKCS#11 config file?

### ISSUE THREAD

**Issue by satanu01** [MatthiasValvekens/pyHanko#19]
Where we find the config file for configuring the cert label changes/assignment purpose...

Like:
```
pkcs11-setups:
  test-setup:
    module-path: /usr/lib/libsofthsm2.so
    token-label: testrsa
    cert-label: signer
    user-pin: 1234
```
