### ISSUE TITLE
Cannot modify font-size via yml config file in text stamp style.

### ISSUE THREAD

**Issue by GorjanP** [MatthiasValvekens/pyHanko#89]
**Describe the bug**
Cannot modify font-size via yml config file in text stamp style. 

**To Reproduce**
To reproduce, use the following yml config.
```
stamp-styles:
    default:
        type: text
        background: signature.png
        stamp-text: "Signed by %(signer)s\nTimestamp: %(ts)s"
        text-box-style:
            font-size: 32
```

Note that in this example `background: signature.png` works perfectly fine and changes the background according to the corresponding file.

**Expected behavior**
Expected output: the font is increased to 32 from the default value of 10. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.8.9
 - PyHanko 0.12.1
